### ISSUE TITLE
is there a query syntax for the search field?

### ISSUE THREAD

**Issue by rajohn96** [OSERAF/MASTERImpl#11]
subject line say it all; neither * nor ? (which are part of lucene search syntax) seem to work.

**Comment by nhambletCCRI** [comment]
At the moment, the query syntax is backing-store specific. For an in-memory TinkerGraph, the query is taken as literal string containment. For, for example, an OrientDB implementation, % can be used as a wildcard.

Exposing this information to the user is worth doing at some point. For now, we can try to get it documented in the wiki.
