### ISSUE TITLE
graph dataset displayed is not consistent with table data set displayed; see screenshot

### ISSUE THREAD

**Issue by rajohn96** [OSERAF/MASTERImpl#8]
In the attached image you will see that several of the nodes shown in the table are not shown in the graph. This was produced after several runs of search, merge, deduplicate were done.

![162 223 12 135 2014-11-10 9 58 35](https://cloud.githubusercontent.com/assets/7251298/4977740/1231b884-68ea-11e4-987f-ebc4c8ce6739.png)

**Comment by nhambletCCRI** [comment]
I'm going to close this. When we can re-produce it, I'll be happy to see a new ticket.
